import * as fs from "fs";
import * as path from "path";
import { Plugin } from "vite";

interface TorchlightVitePluginOptions {
  rootFolder?: string;
  outputPath?: string;
}

export function torchlightVitePlugin(
  options: TorchlightVitePluginOptions = {}
): Plugin {
  const { rootFolder = "src", outputPath = "torchlight.gen.ts" } = options;

  let config: any;
  const tourIds = new Set<string>();
  let isDevMode = false;

  // Function to generate the types file
  const generateTypesFile = () => {
    const sortedTourIds = Array.from(tourIds).sort();

    if (sortedTourIds.length === 0) {
      console.log(
        "⚠️ No tour IDs found. Make sure you have useTorchlightSteps calls in your code."
      );
      return;
    }

    const content = `
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// Auto-generated by torchlight-vite-plugin
// Do not edit this file manually
// Generated on: ${new Date().toISOString()}

// Extend the TorchlightToursRegistry interface from the react-torchlight package
declare module "react-torchlight" {
  interface TorchlightToursRegistry {
${sortedTourIds.map((id) => `    "${id}": "${id}";`).join("\n")}
  }
}

// Export the tour IDs for runtime use
export const TOUR_IDS = {
${sortedTourIds
  .map(
    (id, index) =>
      `  ${id.replace(/[^a-zA-Z0-9_]/g, "_")}: "${id}"${
        index < sortedTourIds.length - 1 ? "," : ""
      }`
  )
  .join("\n")}
} as const;

export type TourId = ${
      sortedTourIds.length > 0
        ? sortedTourIds.map((id) => `"${id}"`).join(" | ")
        : "never"
    };
`;

    // Create the full output path
    const fullOutputPath = path.resolve(rootFolder, outputPath);
    const outputDir = path.dirname(fullOutputPath);

    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(fullOutputPath, content, "utf-8");
    console.log(
      `✅ Generated torchlight types with ${
        tourIds.size
      } tours: ${sortedTourIds.join(", ")}`
    );
  };

  // Function to scan all files during build
  const scanAllFilesForBuild = () => {
    // Don't clear existing tour IDs - rebuild the complete set from all files
    const foundTourIds = new Set<string>();

    const scanDirectory = (dir: string) => {
      try {
        const items = fs.readdirSync(dir);
        for (const item of items) {
          const fullPath = path.join(dir, item);
          const stat = fs.statSync(fullPath);

          if (stat.isDirectory()) {
            // Skip node_modules, dist, and other irrelevant directories
            if (
              !["node_modules", "dist", ".git", ".next", "build"].includes(item)
            ) {
              scanDirectory(fullPath);
            }
          } else if (
            stat.isFile() &&
            (item.endsWith(".ts") || item.endsWith(".tsx"))
          ) {
            // Skip declaration files and the generated file itself
            if (!item.endsWith(".d.ts") && !fullPath.includes(outputPath)) {
              try {
                const code = fs.readFileSync(fullPath, "utf-8");
                const useTorchlightStepsRegex =
                  /useTorchlightSteps\s*\(\s*["']([^"']+)["']/g;
                let match;
                while ((match = useTorchlightStepsRegex.exec(code)) !== null) {
                  const tourId = match[1];
                  if (tourId && tourId.trim() !== "" && tourId !== "tourId") {
                    foundTourIds.add(tourId);
                    console.log(`🎯 Found tour ID: ${tourId} in ${fullPath}`);
                  }
                }
              } catch (error) {
                // Ignore files that can't be read
              }
            }
          }
        }
      } catch (error) {
        // Ignore directories that can't be read
      }
    };

    try {
      scanDirectory(path.resolve(rootFolder));

      // Replace the global tourIds with the newly found ones
      tourIds.clear();
      foundTourIds.forEach((id) => tourIds.add(id));

      generateTypesFile();
    } catch (error) {
      console.warn("Could not scan files for tour IDs:", error);
      generateTypesFile();
    }
  };

  return {
    name: "torchlight-vite-plugin",
    configResolved(resolvedConfig) {
      config = resolvedConfig;
      isDevMode = resolvedConfig.command === "serve";
    },
    configureServer(server) {
      // Function to add tour IDs from a single file
      const scanSingleFile = (filePath: string) => {
        try {
          const code = fs.readFileSync(filePath, "utf-8");
          const useTorchlightStepsRegex =
            /useTorchlightSteps\s*\(\s*["']([^"']+)["']/g;
          let match;
          while ((match = useTorchlightStepsRegex.exec(code)) !== null) {
            const tourId = match[1];
            if (tourId && tourId.trim() !== "" && tourId !== "tourId") {
              if (!tourIds.has(tourId)) {
                tourIds.add(tourId);
                console.log(`🎯 Found new tour ID: ${tourId} in ${filePath}`);
                // Only regenerate if we found new tour IDs
                setTimeout(() => generateTypesFile(), 50);
              }
            }
          }
        } catch (error) {
          // Ignore files that can't be read
        }
      };

      // Function to do a complete rebuild by scanning all files
      const rebuildAllTourIds = () => {
        console.log("🔄 Rebuilding complete tour ID list...");
        const foundTourIds = new Set<string>();

        const scanDirectory = (dir: string) => {
          try {
            const items = fs.readdirSync(dir);
            for (const item of items) {
              const fullPath = path.join(dir, item);
              const stat = fs.statSync(fullPath);

              if (stat.isDirectory()) {
                // Skip node_modules, dist, and other irrelevant directories
                if (
                  !["node_modules", "dist", ".git", ".next", "build"].includes(
                    item
                  )
                ) {
                  scanDirectory(fullPath);
                }
              } else if (
                stat.isFile() &&
                (item.endsWith(".ts") || item.endsWith(".tsx"))
              ) {
                // Skip declaration files and the generated file itself
                if (!item.endsWith(".d.ts") && !fullPath.includes(outputPath)) {
                  try {
                    const code = fs.readFileSync(fullPath, "utf-8");
                    const useTorchlightStepsRegex =
                      /useTorchlightSteps\s*\(\s*["']([^"']+)["']/g;
                    let match;
                    while (
                      (match = useTorchlightStepsRegex.exec(code)) !== null
                    ) {
                      const tourId = match[1];
                      if (
                        tourId &&
                        tourId.trim() !== "" &&
                        tourId !== "tourId"
                      ) {
                        foundTourIds.add(tourId);
                      }
                    }
                  } catch (error) {
                    // Ignore files that can't be read
                  }
                }
              }
            }
          } catch (error) {
            // Ignore directories that can't be read
          }
        };

        scanDirectory(path.resolve(rootFolder));

        // Only update if the found tour IDs are different
        const foundArray = Array.from(foundTourIds).sort();
        const currentArray = Array.from(tourIds).sort();

        if (foundArray.join(",") !== currentArray.join(",")) {
          tourIds.clear();
          foundTourIds.forEach((id) => tourIds.add(id));
          console.log(`✅ Updated tour IDs: ${foundArray.join(", ")}`);
          generateTypesFile();
        }
      };

      // Watch for file changes and regenerate types
      server.watcher.on("change", (file) => {
        if (file.endsWith(".ts") || file.endsWith(".tsx")) {
          // Do a complete rebuild to catch any removed tour IDs
          setTimeout(() => {
            rebuildAllTourIds();
          }, 100); // Small delay to ensure file is written
        }
      });

      // Initial complete scan
      setTimeout(() => {
        rebuildAllTourIds();
      }, 500);
    },
    transform(code, id) {
      // Only process TypeScript/TSX files
      if (!id.endsWith(".ts") && !id.endsWith(".tsx")) {
        return null;
      }

      // Skip the generated file itself
      if (id.includes("torchlight.gen.ts")) {
        return null;
      }

      // Simple regex-based extraction for tour IDs
      // This is a simplified version - the TypeScript plugin provides more robust parsing
      const useTorchlightStepsRegex =
        /useTorchlightSteps\s*\(\s*["']([^"']+)["']/g;

      let match;
      while ((match = useTorchlightStepsRegex.exec(code)) !== null) {
        const tourId = match[1];
        if (tourId && tourId.trim() !== "" && tourId !== "tourId") {
          tourIds.add(tourId);
          console.log(`🎯 Found tour ID: ${tourId} in ${id}`);
        }
      }

      return null;
    },
    generateBundle() {
      // This runs during build mode
      if (!isDevMode) {
        scanAllFilesForBuild();
      }
    },
    closeBundle() {
      // This runs after the bundle is closed, which happens in both dev and build
      if (!isDevMode) {
        scanAllFilesForBuild();
      }
    },
  };
}
