import * as fs from "fs";
import * as path from "path";
import { Plugin } from "vite";

interface VitePluginToursOptions {
  rootFolder?: string;
  outputPath?: string;
}

export function vitePluginTours(options: VitePluginToursOptions = {}): Plugin {
  const { rootFolder = "src", outputPath = "generated-tour-types.d.ts" } =
    options;

  let config: any;
  const tourIds = new Set<string>();

  return {
    name: "vite-plugin-tours",
    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },
    transform(code, id) {
      // Only process TypeScript/TSX files
      if (!id.endsWith(".ts") && !id.endsWith(".tsx")) {
        return null;
      }

      // Skip the generated file itself
      if (id.includes("generated-tour-types.d.ts")) {
        return null;
      }

      // Simple regex-based extraction for tour IDs
      // This is a simplified version - the TypeScript plugin provides more robust parsing
      const useSpotlightStepsRegex =
        /useSpotlightSteps\s*\(\s*["']([^"']+)["']/g;
      const defineToursRegex = /defineTours\s*\(\s*\{([^}]+)\}/g;

      let match;
      while ((match = useSpotlightStepsRegex.exec(code)) !== null) {
        const tourId = match[1];
        if (tourId && tourId.trim() !== "" && tourId !== "tourId") {
          tourIds.add(tourId);
        }
      }

      // Extract from defineTours calls
      while ((match = defineToursRegex.exec(code)) !== null) {
        const tourObject = match[1];
        const propertyRegex = /(\w+)\s*:/g;
        let propMatch;
        while ((propMatch = propertyRegex.exec(tourObject)) !== null) {
          tourIds.add(propMatch[1]);
        }
      }

      return null;
    },
    generateBundle() {
      const sortedTourIds = Array.from(tourIds).sort();

      if (sortedTourIds.length === 0) {
        return;
      }

      const content = `// Auto-generated by vite-plugin-tours
// Do not edit this file manually
// Generated on: ${new Date().toISOString()}

declare module "ReactSpotlight" {
  interface SpotlightToursRegistry {
${sortedTourIds.map((id) => `    "${id}": never;`).join("\n")}
  }
}

// Export the tour IDs for runtime use
export const TOUR_IDS = {
${sortedTourIds
  .map(
    (id, index) =>
      `  ${id.replace(/[^a-zA-Z0-9_]/g, "_")}: "${id}"${
        index < sortedTourIds.length - 1 ? "," : ""
      }`
  )
  .join("\n")}
} as const;

export type TourId = ${sortedTourIds.map((id) => `"${id}"`).join(" | ")};
`;

      const outputDir = path.join(rootFolder, path.dirname(outputPath));
      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      fs.writeFileSync(outputPath, content, "utf-8");
      console.log(
        `✅ Generated tour types with ${
          tourIds.size
        } tours: ${sortedTourIds.join(", ")}`
      );
    },
  };
}
