import React from "react";
import { TorchlightOverlay } from "./components/torchlight-overlay";
import { TorchlightInternalProvider } from "./context";

// Import generated types (will be created by the plugin)
// The file will be generated by the TypeScript plugin when tours are defined
declare global {
  interface TorchlightToursRegistry {}
}

// Fallback types when generated file doesn't exist yet
type TOUR_IDS = Record<string, string>;
type TourId = string;

// Re-export everything from context
export {
  TorchlightContext,
  TorchlightInternalProvider,
  useTorchlight,
  useTorchlightSteps,
} from "./context";

// Re-export components
export { TorchlightOverlay } from "./components/torchlight-overlay";

// Re-export plugins
export {
  createTransformer as torchlightTypeScriptPlugin,
  default as createTypeScriptPlugin,
} from "./plugins/typescript";
export { torchlightVitePlugin } from "./plugins/vite";

// Re-export the generated types for convenience
export type { TOUR_IDS, TourId };

// Re-export types from types.ts
export type {
  TorchlightContextProps,
  TorchlightProviderProps,
  TorchlightStep,
  TorchlightTour,
} from "./types";

// Create a provider that includes the overlay
export const TorchlightProvider: React.FC<{
  children: React.ReactNode;
  overlayProps?: any;
}> = ({ children, overlayProps = {} }) => {
  return (
    <TorchlightInternalProvider overlayProps={overlayProps}>
      {children}
      <TorchlightOverlay {...overlayProps} />
    </TorchlightInternalProvider>
  );
};
